apiVersion: apps/v1
kind: Deployment
metadata:
  name: silksong-frontend
  namespace: silksong
  labels:
    app: silksong-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silksong-frontend
  template:
    metadata:
      labels:
        app: silksong-frontend
    spec:
      containers:
        - name: frontend
          image: vrouqen/front-kubernetes:main
          ports:
            - containerPort: 888
          readinessProbe:
            httpGet:
              path: /
              port: 888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 888
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"